server:
  port: ${PORT:5000}

base-url: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html

rollbar_token: d13cf54f5e6046f98373e5f23b9a9a07

spring:
  application:
    name: app

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate