server:
  port: ${PORT:5000}

base-url: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html

rollbar_token: d13cf54f5e6046f98373e5f23b9a9a07

spring:
  datasource:
    url: "jdbc:h2:./project73db"
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  application:
    name: app

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update